/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ej1_segundo_trimestre;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;

/**
 *
 * @author TeodorAndreiMardale
 */
public class TratamientoDeTexto extends javax.swing.JFrame {

    /**
     * Creates new form TratamientoDeTexto
     */
    public TratamientoDeTexto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupFondo = new javax.swing.ButtonGroup();
        buttonGroupAlineacion = new javax.swing.ButtonGroup();
        jLabelTratTexto = new javax.swing.JLabel();
        jTextFieldEstoEsTexto = new javax.swing.JTextField();
        jLabelFondo = new javax.swing.JLabel();
        jRadioButtonRojo = new javax.swing.JRadioButton();
        jRadioButtonVerde = new javax.swing.JRadioButton();
        jLabelAlineacion = new javax.swing.JLabel();
        jRadioButtonIzq = new javax.swing.JRadioButton();
        jRadioButtonCentro = new javax.swing.JRadioButton();
        jRadioButtonDerecha = new javax.swing.JRadioButton();
        jCheckBoxCursiva = new javax.swing.JCheckBox();
        jCheckBoxNegrita = new javax.swing.JCheckBox();
        jButtonAutor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tratamiento de texto");

        jLabelTratTexto.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabelTratTexto.setForeground(new java.awt.Color(255, 51, 51));
        jLabelTratTexto.setText("Tratamiento de Texto");

        jTextFieldEstoEsTexto.setColumns(40);
        jTextFieldEstoEsTexto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldEstoEsTexto.setText("Esto es Texto");
        jTextFieldEstoEsTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEstoEsTextoActionPerformed(evt);
            }
        });

        jLabelFondo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelFondo.setForeground(new java.awt.Color(0, 102, 255));
        jLabelFondo.setText("Fondo");

        buttonGroupFondo.add(jRadioButtonRojo);
        jRadioButtonRojo.setText("Rojo");
        jRadioButtonRojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRojoActionPerformed(evt);
            }
        });

        buttonGroupFondo.add(jRadioButtonVerde);
        jRadioButtonVerde.setText("Verde");
        jRadioButtonVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonVerdeActionPerformed(evt);
            }
        });

        jLabelAlineacion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelAlineacion.setForeground(new java.awt.Color(0, 102, 51));
        jLabelAlineacion.setText("Alineación");

        buttonGroupAlineacion.add(jRadioButtonIzq);
        jRadioButtonIzq.setText("Izq");
        jRadioButtonIzq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonIzqActionPerformed(evt);
            }
        });

        buttonGroupAlineacion.add(jRadioButtonCentro);
        jRadioButtonCentro.setText("Centro");
        jRadioButtonCentro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCentroActionPerformed(evt);
            }
        });

        buttonGroupAlineacion.add(jRadioButtonDerecha);
        jRadioButtonDerecha.setText("Derch");
        jRadioButtonDerecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDerechaActionPerformed(evt);
            }
        });

        jCheckBoxCursiva.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        jCheckBoxCursiva.setText("Cursiva");
        jCheckBoxCursiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxCursivaActionPerformed(evt);
            }
        });

        jCheckBoxNegrita.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jCheckBoxNegrita.setText("Negrita");
        jCheckBoxNegrita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxNegritaActionPerformed(evt);
            }
        });

        jButtonAutor.setText("Autor");
        jButtonAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAutorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldEstoEsTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCheckBoxCursiva)
                                            .addComponent(jCheckBoxNegrita))
                                        .addGap(226, 226, 226))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButtonRojo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRadioButtonVerde)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jRadioButtonIzq)
                                        .addGap(18, 18, 18))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabelFondo)
                                .addGap(211, 211, 211)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelAlineacion)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButtonCentro)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRadioButtonDerecha)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAutor)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jLabelTratTexto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabelTratTexto)
                .addGap(27, 27, 27)
                .addComponent(jTextFieldEstoEsTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFondo)
                    .addComponent(jLabelAlineacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonCentro)
                    .addComponent(jRadioButtonIzq)
                    .addComponent(jRadioButtonDerecha)
                    .addComponent(jRadioButtonRojo)
                    .addComponent(jRadioButtonVerde))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBoxCursiva)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBoxNegrita)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonAutor)
                        .addContainerGap())))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldEstoEsTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEstoEsTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEstoEsTextoActionPerformed

    private void jRadioButtonRojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRojoActionPerformed
        if (jRadioButtonRojo.isSelected()) {
            jTextFieldEstoEsTexto.setBackground(Color.red);
        }
    }//GEN-LAST:event_jRadioButtonRojoActionPerformed

    private void jRadioButtonIzqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonIzqActionPerformed
        if (jRadioButtonIzq.isSelected()) {
            jTextFieldEstoEsTexto.setHorizontalAlignment(jTextFieldEstoEsTexto.LEFT);
        }
    }//GEN-LAST:event_jRadioButtonIzqActionPerformed

    private void jButtonAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAutorActionPerformed
        JOptionPane.showMessageDialog(null, "Teodor Mardale");
    }//GEN-LAST:event_jButtonAutorActionPerformed

    private void jRadioButtonVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonVerdeActionPerformed
        if (jRadioButtonVerde.isSelected()) {
            jTextFieldEstoEsTexto.setBackground(Color.green);
        }
    }//GEN-LAST:event_jRadioButtonVerdeActionPerformed

    private void jRadioButtonCentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCentroActionPerformed
        if (jRadioButtonCentro.isSelected()) {
            jTextFieldEstoEsTexto.setHorizontalAlignment(jTextFieldEstoEsTexto.CENTER);
        }
    }//GEN-LAST:event_jRadioButtonCentroActionPerformed

    private void jRadioButtonDerechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDerechaActionPerformed
        if (jRadioButtonDerecha.isSelected()) {
            jTextFieldEstoEsTexto.setHorizontalAlignment(jTextFieldEstoEsTexto.RIGHT);
        }
    }//GEN-LAST:event_jRadioButtonDerechaActionPerformed

    private void jCheckBoxCursivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxCursivaActionPerformed
        if (jCheckBoxCursiva.isSelected()) {
            Font italicFont = new Font("Tahoma", Font.ITALIC, 11);
            jTextFieldEstoEsTexto.setFont(italicFont);
        }
        if (jCheckBoxNegrita.isSelected() && jCheckBoxCursiva.isSelected()) {
            Font boldFont = new Font("Tahoma", Font.BOLD | Font.ITALIC, 11);
            jTextFieldEstoEsTexto.setFont(boldFont);
        } 
        if (jCheckBoxCursiva.isSelected() && !jCheckBoxNegrita.isSelected()) {
            Font italicFont = new Font("Tahoma", Font.ITALIC, 11);
            jTextFieldEstoEsTexto.setFont(italicFont);
        }
        if (!jCheckBoxCursiva.isSelected() && jCheckBoxNegrita.isSelected()) {
            Font boldFont = new Font("Tahoma", Font.BOLD, 11);
            jTextFieldEstoEsTexto.setFont(boldFont);
        }
        if (!jCheckBoxNegrita.isSelected() && !jCheckBoxCursiva.isSelected()) {
            Font plainFont = new Font("Tahoma", Font.PLAIN, 11);
            jTextFieldEstoEsTexto.setFont(plainFont);
        }
    }//GEN-LAST:event_jCheckBoxCursivaActionPerformed

    private void jCheckBoxNegritaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxNegritaActionPerformed
        if (jCheckBoxNegrita.isSelected()) {
            Font boldFont = new Font("Tahoma", Font.BOLD, 11);
            jTextFieldEstoEsTexto.setFont(boldFont);
        }
        if (jCheckBoxCursiva.isSelected() && jCheckBoxNegrita.isSelected()) {
            Font italicFont = new Font("Tahoma", Font.BOLD | Font.ITALIC, 11);
            jTextFieldEstoEsTexto.setFont(italicFont);
        }
        if (jCheckBoxNegrita.isSelected() && !jCheckBoxCursiva.isSelected()) {
            Font boldFont = new Font("Tahoma", Font.BOLD, 11);
            jTextFieldEstoEsTexto.setFont(boldFont);
        }
        if (!jCheckBoxNegrita.isSelected() && jCheckBoxCursiva.isSelected()) {
            Font italicFont = new Font("Tahoma", Font.ITALIC, 11);
            jTextFieldEstoEsTexto.setFont(italicFont);
        }
        if (!jCheckBoxNegrita.isSelected() && !jCheckBoxCursiva.isSelected()) {
            Font plainFont = new Font("Tahoma", Font.PLAIN, 11);
            jTextFieldEstoEsTexto.setFont(plainFont);
        }
    }//GEN-LAST:event_jCheckBoxNegritaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TratamientoDeTexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TratamientoDeTexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TratamientoDeTexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TratamientoDeTexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TratamientoDeTexto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupAlineacion;
    private javax.swing.ButtonGroup buttonGroupFondo;
    private javax.swing.JButton jButtonAutor;
    private javax.swing.JCheckBox jCheckBoxCursiva;
    private javax.swing.JCheckBox jCheckBoxNegrita;
    private javax.swing.JLabel jLabelAlineacion;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelTratTexto;
    private javax.swing.JRadioButton jRadioButtonCentro;
    private javax.swing.JRadioButton jRadioButtonDerecha;
    private javax.swing.JRadioButton jRadioButtonIzq;
    private javax.swing.JRadioButton jRadioButtonRojo;
    private javax.swing.JRadioButton jRadioButtonVerde;
    private javax.swing.JTextField jTextFieldEstoEsTexto;
    // End of variables declaration//GEN-END:variables
}
