/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tarea2;

/**
 *
 * @author TeodorAndreiMardale
 */
public class MainScreen extends javax.swing.JFrame {
    
    private SecondaryScreen secondaryScreen;

    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();
        jPanelPelicula.setVisible(false);
        jPanelComida.setVisible(false);
        jPanelVideojuego.setVisible(false);
        jPanelPais.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPelicula = new javax.swing.JPanel();
        jLabelPelicula = new javax.swing.JLabel();
        jTextFieldPeliculaIntroducida = new javax.swing.JTextField();
        jPanelComida = new javax.swing.JPanel();
        jLabelComida = new javax.swing.JLabel();
        jTextFieldComidaIntroducida = new javax.swing.JTextField();
        jPanelVideojuego = new javax.swing.JPanel();
        jLabelVideojuego = new javax.swing.JLabel();
        jTextFieldVideojuegoIntroducido = new javax.swing.JTextField();
        jPanelPais = new javax.swing.JPanel();
        jLabelPais = new javax.swing.JLabel();
        jTextFieldPaisIntroducido = new javax.swing.JTextField();
        jPanelSelec = new javax.swing.JPanel();
        jLabelSelecOpc = new javax.swing.JLabel();
        jPanelOpciones = new javax.swing.JPanel();
        jButtonPelicula = new javax.swing.JButton();
        jButtonComida = new javax.swing.JButton();
        jButtonVideojuego = new javax.swing.JButton();
        jButtonPais = new javax.swing.JButton();
        jButtonValidar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tarea 2");
        getContentPane().setLayout(new java.awt.GridLayout(0, 1));

        jPanelPelicula.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelPelicula.setText("Película:");
        jPanelPelicula.add(jLabelPelicula);

        jTextFieldPeliculaIntroducida.setColumns(83);
        jTextFieldPeliculaIntroducida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPeliculaIntroducidaActionPerformed(evt);
            }
        });
        jPanelPelicula.add(jTextFieldPeliculaIntroducida);

        getContentPane().add(jPanelPelicula);

        jPanelComida.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelComida.setText("Comida:");
        jPanelComida.add(jLabelComida);

        jTextFieldComidaIntroducida.setColumns(83);
        jPanelComida.add(jTextFieldComidaIntroducida);

        getContentPane().add(jPanelComida);

        jPanelVideojuego.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelVideojuego.setText("Videojuego:");
        jPanelVideojuego.add(jLabelVideojuego);

        jTextFieldVideojuegoIntroducido.setColumns(81);
        jPanelVideojuego.add(jTextFieldVideojuegoIntroducido);

        getContentPane().add(jPanelVideojuego);

        jPanelPais.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelPais.setText("País:");
        jPanelPais.add(jLabelPais);

        jTextFieldPaisIntroducido.setColumns(85);
        jPanelPais.add(jTextFieldPaisIntroducido);

        getContentPane().add(jPanelPais);

        jPanelSelec.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelSelecOpc.setText("Seleccione cualquiera de las opciones (puede ocultar y volver a mostrar la opción seleccionada) ");
        jPanelSelec.add(jLabelSelecOpc);

        getContentPane().add(jPanelSelec);

        jPanelOpciones.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonPelicula.setText("Película/s favorita/s");
        jButtonPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPeliculaActionPerformed(evt);
            }
        });
        jPanelOpciones.add(jButtonPelicula);

        jButtonComida.setText("Comida/s favorita/s");
        jButtonComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComidaActionPerformed(evt);
            }
        });
        jPanelOpciones.add(jButtonComida);

        jButtonVideojuego.setText("Videojuego/s favorito/s");
        jButtonVideojuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVideojuegoActionPerformed(evt);
            }
        });
        jPanelOpciones.add(jButtonVideojuego);

        jButtonPais.setText("País/es favorito/s");
        jButtonPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPaisActionPerformed(evt);
            }
        });
        jPanelOpciones.add(jButtonPais);

        getContentPane().add(jPanelOpciones);

        jButtonValidar.setText("Validar");
        jButtonValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValidarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonValidar);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPeliculaActionPerformed
        if (jPanelPelicula.isVisible()) {
           jPanelPelicula.setVisible(false); 
        } else {
            jPanelPelicula.setVisible(true);
        }
    }//GEN-LAST:event_jButtonPeliculaActionPerformed

    private void jButtonComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComidaActionPerformed
        if (jPanelComida.isVisible()) {
           jPanelComida.setVisible(false); 
        } else {
            jPanelComida.setVisible(true);
        }
    }//GEN-LAST:event_jButtonComidaActionPerformed

    private void jButtonVideojuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVideojuegoActionPerformed
        if (jPanelVideojuego.isVisible()) {
           jPanelVideojuego.setVisible(false); 
        } else {
            jPanelVideojuego.setVisible(true);
        }
    }//GEN-LAST:event_jButtonVideojuegoActionPerformed

    private void jButtonPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPaisActionPerformed
        if (jPanelPais.isVisible()) {
           jPanelPais.setVisible(false); 
        } else {
            jPanelPais.setVisible(true);
        }
    }//GEN-LAST:event_jButtonPaisActionPerformed

    private void jButtonValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValidarActionPerformed
        SecondaryScreen secondaryScreen = new SecondaryScreen(this, false);
        secondaryScreen.setVisible(true);
        if (jTextFieldPeliculaIntroducida.getText().isEmpty()) {
            secondaryScreen.establecerPelicula("Valor no introducido");
        } else {
            String pelicula = jTextFieldPeliculaIntroducida.getText();
            secondaryScreen.establecerPelicula(pelicula);
        }
        if (jTextFieldComidaIntroducida.getText().isEmpty()) {
            secondaryScreen.establecerComida("Valor no introducido");
        } else {
            String comida = jTextFieldComidaIntroducida.getText();
            secondaryScreen.establecerComida(comida);
        }
        if (jTextFieldVideojuegoIntroducido.getText().isEmpty()) {
            secondaryScreen.establecerVideojuego("Valor no introducido");
        } else {
            String videojuego = jTextFieldVideojuegoIntroducido.getText();
            secondaryScreen.establecerVideojuego(videojuego);
        }
        if (jTextFieldPaisIntroducido.getText().isEmpty()) {
            secondaryScreen.establecerPais("Valor no introducido");
        } else {
            String pais = jTextFieldPaisIntroducido.getText();
            secondaryScreen.establecerPais(pais);
        }
    }//GEN-LAST:event_jButtonValidarActionPerformed

    private void jTextFieldPeliculaIntroducidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPeliculaIntroducidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPeliculaIntroducidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonComida;
    private javax.swing.JButton jButtonPais;
    private javax.swing.JButton jButtonPelicula;
    private javax.swing.JButton jButtonValidar;
    private javax.swing.JButton jButtonVideojuego;
    private javax.swing.JLabel jLabelComida;
    private javax.swing.JLabel jLabelPais;
    private javax.swing.JLabel jLabelPelicula;
    private javax.swing.JLabel jLabelSelecOpc;
    private javax.swing.JLabel jLabelVideojuego;
    private javax.swing.JPanel jPanelComida;
    private javax.swing.JPanel jPanelOpciones;
    private javax.swing.JPanel jPanelPais;
    private javax.swing.JPanel jPanelPelicula;
    private javax.swing.JPanel jPanelSelec;
    private javax.swing.JPanel jPanelVideojuego;
    private javax.swing.JTextField jTextFieldComidaIntroducida;
    private javax.swing.JTextField jTextFieldPaisIntroducido;
    private javax.swing.JTextField jTextFieldPeliculaIntroducida;
    private javax.swing.JTextField jTextFieldVideojuegoIntroducido;
    // End of variables declaration//GEN-END:variables
}
