/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tarea2;

/**
 *
 * @author TeodorAndreiMardale
 */
public class MainScreen extends javax.swing.JFrame {
    
    private SecondaryScreen secondaryScreen;

    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();
        jPanelPelicula.setVisible(false);
        jPanelComida.setVisible(false);
        jPanelVideojuego.setVisible(false);
        jPanelPais.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPelicula = new javax.swing.JPanel();
        jLabelPelicula = new javax.swing.JLabel();
        jTextFieldPeliculaIntroducida = new javax.swing.JTextField();
        jPanelOpciones = new javax.swing.JPanel();
        jButtonPelicula = new javax.swing.JButton();
        jButtonComida = new javax.swing.JButton();
        jButtonVideojuego = new javax.swing.JButton();
        jLabelSelecOpc = new javax.swing.JLabel();
        jButtonPais = new javax.swing.JButton();
        jPanelComida = new javax.swing.JPanel();
        jLabelComida = new javax.swing.JLabel();
        jTextFieldComidaIntroducida = new javax.swing.JTextField();
        jPanelVideojuego = new javax.swing.JPanel();
        jLabelVideojuego = new javax.swing.JLabel();
        jTextFieldVideojuegoIntroducido = new javax.swing.JTextField();
        jPanelPais = new javax.swing.JPanel();
        jLabelPais = new javax.swing.JLabel();
        jTextFieldPaisIntroducido = new javax.swing.JTextField();
        jButtonValidar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelPelicula.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelPelicula.setText("Película:");

        javax.swing.GroupLayout jPanelPeliculaLayout = new javax.swing.GroupLayout(jPanelPelicula);
        jPanelPelicula.setLayout(jPanelPeliculaLayout);
        jPanelPeliculaLayout.setHorizontalGroup(
            jPanelPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPeliculaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabelPelicula)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldPeliculaIntroducida, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanelPeliculaLayout.setVerticalGroup(
            jPanelPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPeliculaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPeliculaIntroducida, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jLabelPelicula))
                .addContainerGap())
        );

        jPanelOpciones.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonPelicula.setText("Película/s favorita/s");
        jButtonPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPeliculaActionPerformed(evt);
            }
        });

        jButtonComida.setText("Comida/s favorita/s");
        jButtonComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComidaActionPerformed(evt);
            }
        });

        jButtonVideojuego.setText("Videojuego/s favorito/s");
        jButtonVideojuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVideojuegoActionPerformed(evt);
            }
        });

        jLabelSelecOpc.setText("Seleccione una de las opciones (tras seleccionar la opción, puede introducir varias opciones)");

        jButtonPais.setText("País/es favorito/s");
        jButtonPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPaisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelOpcionesLayout = new javax.swing.GroupLayout(jPanelOpciones);
        jPanelOpciones.setLayout(jPanelOpcionesLayout);
        jPanelOpcionesLayout.setHorizontalGroup(
            jPanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpcionesLayout.createSequentialGroup()
                .addGroup(jPanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelOpcionesLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabelSelecOpc)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelOpcionesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonPelicula)
                        .addGap(39, 39, 39)
                        .addComponent(jButtonComida)
                        .addGap(35, 35, 35)
                        .addComponent(jButtonVideojuego)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(jButtonPais)))
                .addContainerGap())
        );
        jPanelOpcionesLayout.setVerticalGroup(
            jPanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpcionesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelSelecOpc)
                .addGap(18, 18, 18)
                .addGroup(jPanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPelicula)
                    .addComponent(jButtonComida)
                    .addComponent(jButtonVideojuego)
                    .addComponent(jButtonPais))
                .addGap(17, 17, 17))
        );

        jPanelComida.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelComida.setText("Comida:");

        javax.swing.GroupLayout jPanelComidaLayout = new javax.swing.GroupLayout(jPanelComida);
        jPanelComida.setLayout(jPanelComidaLayout);
        jPanelComidaLayout.setHorizontalGroup(
            jPanelComidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComidaLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabelComida)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldComidaIntroducida, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelComidaLayout.setVerticalGroup(
            jPanelComidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComidaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelComidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldComidaIntroducida, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jLabelComida))
                .addContainerGap())
        );

        jPanelVideojuego.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelVideojuego.setText("Videojuego:");

        javax.swing.GroupLayout jPanelVideojuegoLayout = new javax.swing.GroupLayout(jPanelVideojuego);
        jPanelVideojuego.setLayout(jPanelVideojuegoLayout);
        jPanelVideojuegoLayout.setHorizontalGroup(
            jPanelVideojuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVideojuegoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabelVideojuego)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldVideojuegoIntroducido, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelVideojuegoLayout.setVerticalGroup(
            jPanelVideojuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVideojuegoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVideojuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldVideojuegoIntroducido, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jLabelVideojuego))
                .addContainerGap())
        );

        jPanelPais.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelPais.setText("País:");

        javax.swing.GroupLayout jPanelPaisLayout = new javax.swing.GroupLayout(jPanelPais);
        jPanelPais.setLayout(jPanelPaisLayout);
        jPanelPaisLayout.setHorizontalGroup(
            jPanelPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPaisLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabelPais)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldPaisIntroducido, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelPaisLayout.setVerticalGroup(
            jPanelPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPaisIntroducido, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jLabelPais))
                .addContainerGap())
        );

        jButtonValidar.setText("Validar");
        jButtonValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValidarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelPais, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelVideojuego, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelComida, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelPelicula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jPanelOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(335, 335, 335)
                        .addComponent(jButtonValidar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelComida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelVideojuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jButtonValidar)
                .addGap(18, 18, 18)
                .addComponent(jPanelOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPeliculaActionPerformed
        jPanelPelicula.setVisible(true);
    }//GEN-LAST:event_jButtonPeliculaActionPerformed

    private void jButtonComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComidaActionPerformed
        jPanelComida.setVisible(true);
    }//GEN-LAST:event_jButtonComidaActionPerformed

    private void jButtonVideojuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVideojuegoActionPerformed
        jPanelVideojuego.setVisible(true);
    }//GEN-LAST:event_jButtonVideojuegoActionPerformed

    private void jButtonPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPaisActionPerformed
        jPanelPais.setVisible(true);
    }//GEN-LAST:event_jButtonPaisActionPerformed

    private void jButtonValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValidarActionPerformed
        SecondaryScreen secondaryScreen = new SecondaryScreen(this, true);
        secondaryScreen.setVisible(true);
        String pelicula = jTextFieldPeliculaIntroducida.getText();
        secondaryScreen.establecerPelicula(pelicula);
        String comida = jTextFieldComidaIntroducida.getText();
        secondaryScreen.establecerComida(comida);
        String videojuego = jTextFieldVideojuegoIntroducido.getText();
        secondaryScreen.establecerVideojuego(videojuego);
        String pais = jTextFieldPaisIntroducido.getText();
        secondaryScreen.establecerPais(pais);
    }//GEN-LAST:event_jButtonValidarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonComida;
    private javax.swing.JButton jButtonPais;
    private javax.swing.JButton jButtonPelicula;
    private javax.swing.JButton jButtonValidar;
    private javax.swing.JButton jButtonVideojuego;
    private javax.swing.JLabel jLabelComida;
    private javax.swing.JLabel jLabelPais;
    private javax.swing.JLabel jLabelPelicula;
    private javax.swing.JLabel jLabelSelecOpc;
    private javax.swing.JLabel jLabelVideojuego;
    private javax.swing.JPanel jPanelComida;
    private javax.swing.JPanel jPanelOpciones;
    private javax.swing.JPanel jPanelPais;
    private javax.swing.JPanel jPanelPelicula;
    private javax.swing.JPanel jPanelVideojuego;
    private javax.swing.JTextField jTextFieldComidaIntroducida;
    private javax.swing.JTextField jTextFieldPaisIntroducido;
    private javax.swing.JTextField jTextFieldPeliculaIntroducida;
    private javax.swing.JTextField jTextFieldVideojuegoIntroducido;
    // End of variables declaration//GEN-END:variables
}
