/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.tarea2;

/**
 *
 * @author TeodorAndreiMardale
 */
public class SecondaryScreen extends javax.swing.JDialog {
    
    private MainScreen mainScreen;

    /**
     * Creates new form SecondaryScreen
     */
    public SecondaryScreen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelValores = new javax.swing.JPanel();
        jLabelValorPelicula = new javax.swing.JLabel();
        jLabelValorComida = new javax.swing.JLabel();
        jLabelValorVideojuego = new javax.swing.JLabel();
        jLabelValorPais = new javax.swing.JLabel();
        jPanelValoresIntroducidos = new javax.swing.JPanel();
        jLabelPeliculaIntroducida = new javax.swing.JLabel();
        jLabelComidaIntroducida = new javax.swing.JLabel();
        jLabelVideojuegoIntroducido = new javax.swing.JLabel();
        jLabelPaisIntroducido = new javax.swing.JLabel();
        jPanelVolver = new javax.swing.JPanel();
        jButtonVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Valores introducidos");

        jPanelValores.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelValores.setLayout(new java.awt.GridLayout(4, 1, 10, 20));

        jLabelValorPelicula.setText("Película:");
        jPanelValores.add(jLabelValorPelicula);

        jLabelValorComida.setText("Comida:");
        jPanelValores.add(jLabelValorComida);

        jLabelValorVideojuego.setText("Videojuego:");
        jPanelValores.add(jLabelValorVideojuego);

        jLabelValorPais.setText("País:");
        jPanelValores.add(jLabelValorPais);

        jPanelValoresIntroducidos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelValoresIntroducidos.setLayout(new java.awt.GridLayout(0, 1));
        jPanelValoresIntroducidos.add(jLabelPeliculaIntroducida);
        jPanelValoresIntroducidos.add(jLabelComidaIntroducida);
        jPanelValoresIntroducidos.add(jLabelVideojuegoIntroducido);
        jPanelValoresIntroducidos.add(jLabelPaisIntroducido);

        jPanelVolver.setLayout(new java.awt.GridLayout());

        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });
        jPanelVolver.add(jButtonVolver);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelVolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelValores, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelValoresIntroducidos, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelValores, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .addComponent(jPanelValoresIntroducidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelVolver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        MainScreen mainScreen = new MainScreen();
        mainScreen.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonVolverActionPerformed

    public void establecerPelicula(String pelicula) {
        jLabelPeliculaIntroducida.setText(pelicula);
    }
    
    public void establecerComida(String comida) {
        jLabelComidaIntroducida.setText(comida);
    }
    
    public void establecerVideojuego(String videojuego) {
        jLabelVideojuegoIntroducido.setText(videojuego); 
    }
    
    public void establecerPais(String pais) {
        jLabelPaisIntroducido.setText(pais);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SecondaryScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SecondaryScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SecondaryScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SecondaryScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SecondaryScreen dialog = new SecondaryScreen(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabelComidaIntroducida;
    private javax.swing.JLabel jLabelPaisIntroducido;
    private javax.swing.JLabel jLabelPeliculaIntroducida;
    private javax.swing.JLabel jLabelValorComida;
    private javax.swing.JLabel jLabelValorPais;
    private javax.swing.JLabel jLabelValorPelicula;
    private javax.swing.JLabel jLabelValorVideojuego;
    private javax.swing.JLabel jLabelVideojuegoIntroducido;
    private javax.swing.JPanel jPanelValores;
    private javax.swing.JPanel jPanelValoresIntroducidos;
    private javax.swing.JPanel jPanelVolver;
    // End of variables declaration//GEN-END:variables
}
