/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.checkbox;

/**
 *
 * @author TeodorAndreiMardale
 */
public class CheckBox1 extends javax.swing.JFrame {

    /**
     * Creates new form CheckBox1
     */
    public CheckBox1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxAleman = new javax.swing.JCheckBox();
        jCheckBoxIngles = new javax.swing.JCheckBox();
        jCheckBoxItaliano = new javax.swing.JCheckBox();
        jCheckBoxFrances = new javax.swing.JCheckBox();
        jLabelIdiomas = new javax.swing.JLabel();
        jButtonFinalizar = new javax.swing.JButton();
        jRadioButtonRojo = new javax.swing.JRadioButton();
        jRadioButtonVerde = new javax.swing.JRadioButton();
        jRadioButtonNegro = new javax.swing.JRadioButton();
        jRadioButtonBlanco = new javax.swing.JRadioButton();
        jPanelResultado = new javax.swing.JPanel();
        jLabelResultado = new javax.swing.JLabel();
        jComboBoxCoches = new javax.swing.JComboBox<>();
        jComboBoxColores = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jCheckBoxAleman.setText("Alemán");
        jCheckBoxAleman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAlemanActionPerformed(evt);
            }
        });

        jCheckBoxIngles.setText("Inglés");
        jCheckBoxIngles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxInglesActionPerformed(evt);
            }
        });

        jCheckBoxItaliano.setText("Italiano");
        jCheckBoxItaliano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxItalianoActionPerformed(evt);
            }
        });

        jCheckBoxFrances.setText("Francés");
        jCheckBoxFrances.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxFrancesActionPerformed(evt);
            }
        });

        jButtonFinalizar.setText("Finalizar");

        jRadioButtonRojo.setText("Rojo");
        jRadioButtonRojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRojoActionPerformed(evt);
            }
        });

        jRadioButtonVerde.setText("Verde");
        jRadioButtonVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonVerdeActionPerformed(evt);
            }
        });

        jRadioButtonNegro.setText("Negro");
        jRadioButtonNegro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNegroActionPerformed(evt);
            }
        });

        jRadioButtonBlanco.setText("Blanco");
        jRadioButtonBlanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonBlancoActionPerformed(evt);
            }
        });

        jPanelResultado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanelResultadoLayout = new javax.swing.GroupLayout(jPanelResultado);
        jPanelResultado.setLayout(jPanelResultadoLayout);
        jPanelResultadoLayout.setHorizontalGroup(
            jPanelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResultadoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabelResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelResultadoLayout.setVerticalGroup(
            jPanelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResultadoLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabelResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jComboBoxCoches.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FORD", "KIA", "RENAULT", "SEAT" }));
        jComboBoxCoches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCochesActionPerformed(evt);
            }
        });

        jComboBoxColores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ROJO", "VERDE", "AZUL" }));
        jComboBoxColores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxColoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButtonRojo)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonVerde)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonNegro)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonBlanco))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCheckBoxAleman)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBoxIngles)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBoxItaliano)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBoxFrances))
                            .addComponent(jLabelIdiomas, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addComponent(jButtonFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxCoches, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxColores, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBoxAleman)
                            .addComponent(jCheckBoxIngles)
                            .addComponent(jCheckBoxItaliano)
                            .addComponent(jCheckBoxFrances))
                        .addGap(26, 26, 26)
                        .addComponent(jLabelIdiomas, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonRojo)
                    .addComponent(jRadioButtonVerde)
                    .addComponent(jRadioButtonNegro)
                    .addComponent(jRadioButtonBlanco))
                .addGap(27, 27, 27)
                .addComponent(jComboBoxCoches, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxColores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jPanelResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxFrancesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxFrancesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxFrancesActionPerformed

    private void jComboBoxCochesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCochesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCochesActionPerformed

    private void jComboBoxColoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxColoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxColoresActionPerformed

    private void jCheckBoxAlemanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxAlemanActionPerformed
        String texto = "Idiomas: ";
        
        if(jCheckBoxAleman.isSelected()) {
            texto += "Alemán, ";
        }
        if(jCheckBoxIngles.isSelected()) {
            texto += "Inglés, ";
        }
        if(jCheckBoxItaliano.isSelected()) {
            texto += "Italiano, ";
        }
        if(jCheckBoxFrances.isSelected()) {
            texto += "Francés, ";
        }
        texto = texto.substring(0, texto.length() - 2);
        jLabelIdiomas.setText(texto);
    }//GEN-LAST:event_jCheckBoxAlemanActionPerformed

    private void jCheckBoxInglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxInglesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxInglesActionPerformed

    private void jCheckBoxItalianoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxItalianoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxItalianoActionPerformed

    private void jRadioButtonRojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRojoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonRojoActionPerformed

    private void jRadioButtonVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonVerdeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonVerdeActionPerformed

    private void jRadioButtonNegroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNegroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonNegroActionPerformed

    private void jRadioButtonBlancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonBlancoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonBlancoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckBox1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckBox1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckBox1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckBox1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckBox1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFinalizar;
    private javax.swing.JCheckBox jCheckBoxAleman;
    private javax.swing.JCheckBox jCheckBoxFrances;
    private javax.swing.JCheckBox jCheckBoxIngles;
    private javax.swing.JCheckBox jCheckBoxItaliano;
    private javax.swing.JComboBox<String> jComboBoxCoches;
    private javax.swing.JComboBox<String> jComboBoxColores;
    private javax.swing.JLabel jLabelIdiomas;
    private javax.swing.JLabel jLabelResultado;
    private javax.swing.JPanel jPanelResultado;
    private javax.swing.JRadioButton jRadioButtonBlanco;
    private javax.swing.JRadioButton jRadioButtonNegro;
    private javax.swing.JRadioButton jRadioButtonRojo;
    private javax.swing.JRadioButton jRadioButtonVerde;
    // End of variables declaration//GEN-END:variables
}
